baseURL: "https://ifan-dev.github.io/"
title: Jurnal Ifan
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Jurnal Ifan
  description: "Tempat saya menyimpan hasil googling, mungkin suatu saat bakal dibutuhkan kembali"
  keywords: [Blog, Portfolio, PaperMod]
  author: Ifan Irfansyah
  # author: ["Ifan Irfansyah", "You"] # multiple authors
  images: ["/img/Palestine.png, twitter-cards"]
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Jurnal Ifan"
    icon: /img/Palestine.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Jurnal Ifan
    subtitle: "Sekilas tentang saya"
    imageUrl: "/img/Palestine.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Ifan Irfansyah
    buttons:
      - name: Postingan
        url: posts
      - name: Label
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Assalamu'alaikum \U0001F44B"
    Content: Selamat datang di website tempat saya menyimpan hasil googling, mungkin suatu saat bakal dibutuhkan kembali

  socialIcons:
    - name: instagram
      url: "https://instagram.com/presiden.irfans"
    - name: phone
      url: "https://wa.me/"
    - name: github
      url: "https://github.com/ifan-dev"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Kategori
      url: /categories/
      weight: 10
    - identifier: tags
      name: Label
      url: /tags/
      weight: 20
    - identifier: example
      name: Link Lainnya
      url: /Lainnya/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
